import type { Employee } from "@/types";

export const mockEmployees: Employee[] = [
  {
    id: "1",
    name: "Dianne Russell",
    role: "Senior Product Designer",
    department: "Design",
    status: "active",
    email: "dianne.russell@labourlink.com",
  },
  {
    id: "2",
    name: "Johannes Kepler",
    role: "Software Engineer",
    department: "Engineering",
    status: "active",
    email: "johannes.kepler@labourlink.com",
  },
  {
    id: "3",
    name: "Arlene McCoy",
    role: "Product Manager",
    department: "Product Management",
    status: "on_leave",
    email: "arlene.mccoy@labourlink.com",
  },
  {
    id: "4",
    name: "Albert Flores",
    role: "QA Engineer",
    department: "Engineering",
    status: "inactive",
    email: "albert.flores@labourlink.com",
  },
  {
    id: "5",
    name: "Cody Fisher",
    role: "DevOps Engineer",
    department: "Engineering",
    status: "active",
    email: "cody.fisher@labourlink.com",
  },
  {
    id: "6",
    name: "Esther Howard",
    role: "Marketing Specialist",
    department: "Marketing",
    status: "active",
    email: "esther.howard@labourlink.com",
  },
  {
    id: "7",
    name: "Kristin Watson",
    role: "Head of HR",
    department: "Human Resources",
    status: "active",
    email: "kristin.watson@labourlink.com",
  },
  {
    id: "8",
    name: "Cameron Williamson",
    role: "Frontend Developer",
    department: "Engineering",
    status: "active",
    email: "cameron.williamson@labourlink.com",
  },
  {
    id: "9",
    name: "Leslie Alexander",
    role: "Content Writer",
    department: "Marketing",
    status: "on_leave",
    email: "leslie.alexander@labourlink.com",
  },
  {
    id: "10",
    name: "Eleanor Pena",
    role: "Customer Success Specialist",
    department: "Operations",
    status: "active",
    email: "eleanor.pena@labourlink.com",
  },
  {
    id: "11",
    name: "Devon Lane",
    role: "Operations Manager",
    department: "Operations",
    status: "inactive",
    email: "devon.lane@labourlink.com",
  },
  {
    id: "12",
    name: "Guy Hawkins",
    role: "Backend Engineer",
    department: "Engineering",
    status: "active",
    email: "guy.hawkins@labourlink.com",
  }
];
